export const Topics = [
  "Science and Environment",
  "Marketing and Advertising",
  "Sales and Retail",
  "Technology",
  "Finance and Economy",
  "Health",
  "Business and Management",
  "Lifestyle and Leisure",
  "Society and Culture",
  "Arts and Entertainment",
  "Education and Learning",
  "Sports and Fitness",
  "Careers and Employments",
];

export const JobCategory = [
  "Engineering",
  "Business Development",
  "Finance",
  "Administrative Assistant",
  "Retail Associate",
  "Customer Service",
  "Operations",
  "Information Technology",
  "Marketing",
  "Human Resources",
  "Sales",
  "Program and Project Management",
  "Legal",
  "Accounting",
  "Business Analyst",
  "Arts and Design",
  "Education",
  "Community and Social Services",
  "Consulting",
  "Entrepreneurship",
  "Healthcare",
  "Media and Communications",
];

export const FooterList = [
  {
    name: "General",
    val: [
      "Sign Up",
      "Help Center",
      "About",
      "Press",
      "Blog",
      "Careers",
      "Developers",
    ],
  },
  {
    name: "Browse LinkedIn",
    val: ["Learning", "Jobs", "Salary", "Mobile", "Services", "Products"],
  },
  {
    name: "Business Solutions",
    val: ["Talent", "Marketing", "Sales", "Learning"],
  },
  {
    name: "Directories",
    val: [
      "Companies",
      "Members",
      "Jobs",
      "Companies",
      "Salaries",
      "Featured",
      "Learning",
      "Posts",
      "Articles",
      "Schools",
      "News",
      "News Letters",
      "Services",
      "Interview Prep",
      "Products",
      "Content Topics",
    ],
  },
];

export const FooterList2 = [
  "About",
  "Accessibility",
  "User Agreement",
  "Privacy Policy",
  "Cookie Policy",
  "Copyright Policy",
  "Brand Policy",
  "Guest Controls",
  "Community Guidelines",
];
